FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend backend
COPY alembic.ini .
COPY migrations migrations

EXPOSE 8000

CMD ["/bin/sh", "/app/backend/api/entrypoint.sh"]
